/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package week1exercises;

public class App {

    public static void main(String[] args) {
       //CounterThreads2Covid davidGoggins = new CounterThreads2Covid();
       //Printer printer = new Printer();
       TestLongCounterExperiments t1 = new TestLongCounterExperiments();
    }
}
