/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises01;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", null);
    }

    @Test public void test1() {
        assert(1==2);
    }
}
